import { DrizzleService } from "@/services/drizzle-service.server";
import { createClipOperations } from "@/services/db-clip-operations.server";
import { createVideoOperations } from "@/services/db-video-operations.server";
import { createPlanOperations } from "@/services/db-plan-operations.server";
import { createCourseOperations } from "@/services/db-course-operations.server";
import { createVersionOperations } from "@/services/db-version-operations.server";
import { createLessonSectionOperations } from "@/services/db-lesson-section-operations.server";
import { createLinkAuthOperations } from "@/services/db-link-auth-operations.server";
import { createThumbnailOperations } from "@/services/db-thumbnail-operations.server";
import { Effect } from "effect";

export class DBFunctionsService extends Effect.Service<DBFunctionsService>()(
  "DBFunctionsService",
  {
    effect: Effect.gen(function* () {
      const db = yield* DrizzleService;

      const {
        getClipById,
        getClipsByIds,
        updateClip,
        archiveClip,
        reorderClip,
        createClipSection,
        createClipSectionAtInsertionPoint,
        createClipSectionAtPosition,
        getClipSectionById,
        updateClipSection,
        archiveClipSection,
        reorderClipSection,
        appendClips,
      } = createClipOperations(db);

      const {
        getCourseById,
        getCourseByFilePath,
        getCourseWithSectionsById,
        getCourseWithSlimClipsById,
        getVideoTranscripts,
        getCourseWithSectionsByFilePath,
        getCourses,
        getArchivedCourses,
        createCourse,
        createGhostCourse,
        updateCourseName,
        updateCourseMemory,
        updateCourseArchiveStatus,
        updateCourseFilePath,
        deleteCourse,
      } = createCourseOperations(db);

      const {
        getVideoDeepById,
        getStandaloneVideos,
        getStandaloneVideosSidebar,
        getAllStandaloneVideos,
        getArchivedStandaloneVideos,
        getVideoWithClipsById,
        createVideo,
        createStandaloneVideo,
        hasOriginalFootagePathAlreadyBeenUsed,
        updateVideo,
        deleteVideo,
        updateVideoPath,
        updateVideoLesson,
        updateVideoArchiveStatus,
        getNextVideoId,
        getPreviousVideoId,
        getNextLessonWithoutVideo,
        getVideosForFewShotExamples,
      } = createVideoOperations(db, { getCourseWithSectionsById });

      const {
        getPlans,
        syncPlan,
        deletePlan,
        renamePlan,
        getArchivedPlans,
        updatePlanArchiveStatus,
      } = createPlanOperations(db);

      const {
        getCourseVersions,
        getLatestCourseVersion,
        getCourseVersionById,
        getCourseWithSectionsByVersion,
        getVersionWithSections,
        createCourseVersion,
        updateCourseVersion,
        copyVersionStructure,
        getVideoIdsForVersion,
        getAllVersionsWithStructure,
      } = createVersionOperations(db);

      const {
        getLessonById,
        getLessonsBySectionId,
        getLessonWithHierarchyById,
        getSectionWithHierarchyById,
        createSections,
        createLessons,
        createGhostLesson,
        updateLesson,
        deleteLesson,
        deleteSection,
        updateSectionOrder,
        updateSectionPath,
        updateSectionDescription,
        getSectionsByIds,
        getSectionsByRepoVersionId,
        updateLessonOrder,
        batchUpdateLessonOrders,
        batchUpdateSectionOrders,
      } = createLessonSectionOperations(db);

      const {
        getLinks,
        createLink,
        deleteLink,
        getYoutubeAuth,
        upsertYoutubeAuth,
        updateYoutubeAccessToken,
        deleteYoutubeAuth,
        getAiHeroAuth,
        upsertAiHeroAuth,
        deleteAiHeroAuth,
      } = createLinkAuthOperations(db);

      const {
        getThumbnailsByVideoId,
        createThumbnail,
        getThumbnailById,
        updateThumbnail,
        selectThumbnailForUpload,
        deselectAllThumbnails,
        deleteThumbnail,
      } = createThumbnailOperations(db);

      return {
        getClipById,
        getClipsByIds,
        updateClip,
        archiveClip,
        reorderClip,
        createClipSection,
        createClipSectionAtInsertionPoint,
        createClipSectionAtPosition,
        getClipSectionById,
        updateClipSection,
        archiveClipSection,
        reorderClipSection,
        appendClips,
        getLessonById,
        getLessonWithHierarchyById,
        getLessonsBySectionId,
        getSectionWithHierarchyById,
        createVideo,
        createStandaloneVideo,
        hasOriginalFootagePathAlreadyBeenUsed,
        updateVideo,
        deleteVideo,
        updateVideoPath,
        updateVideoLesson,
        getCourseById,
        getCourseByFilePath,
        getCourseWithSectionsById,
        getCourseWithSlimClipsById,
        getVideoTranscripts,
        getCourseWithSectionsByFilePath,
        getCourses,
        getArchivedCourses,
        getVideoById: getVideoDeepById,
        getVideoWithClipsById: getVideoWithClipsById,
        getStandaloneVideos,
        getStandaloneVideosSidebar,
        getAllStandaloneVideos,
        getArchivedStandaloneVideos,
        createCourse,
        createGhostCourse,
        createSections,
        createLessons,
        createGhostLesson,
        updateLesson,
        deleteLesson,
        deleteSection,
        updateSectionOrder,
        updateSectionPath,
        updateSectionDescription,
        getSectionsByIds,
        getSectionsByRepoVersionId,
        updateLessonOrder,
        batchUpdateLessonOrders,
        batchUpdateSectionOrders,
        getNextVideoId,
        getPreviousVideoId,
        getNextLessonWithoutVideo,
        getCourseVersions,
        getLatestCourseVersion,
        getCourseVersionById,
        getCourseWithSectionsByVersion,
        getVersionWithSections,
        createCourseVersion,
        updateCourseVersion,
        updateCourseName,
        updateCourseMemory,
        updateCourseArchiveStatus,
        updateVideoArchiveStatus,
        updateCourseFilePath,
        deleteCourse,
        copyVersionStructure,
        getVideoIdsForVersion,
        getAllVersionsWithStructure,
        getPlans,
        syncPlan,
        deletePlan,
        renamePlan,
        getArchivedPlans,
        updatePlanArchiveStatus,
        getLinks,
        createLink,
        deleteLink,
        getVideosForFewShotExamples,
        getYoutubeAuth,
        upsertYoutubeAuth,
        updateYoutubeAccessToken,
        deleteYoutubeAuth,
        getAiHeroAuth,
        upsertAiHeroAuth,
        deleteAiHeroAuth,
        getThumbnailsByVideoId,
        createThumbnail,
        getThumbnailById,
        updateThumbnail,
        selectThumbnailForUpload,
        deselectAllThumbnails,
        deleteThumbnail,
      };
    }),
  }
) {}
